"""add create_at to songs

Revision ID: da437b1a8b4e
Revises: 3b99fd207f92
Create Date: 2025-08-22 12:50:45.168352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da437b1a8b4e'
down_revision: Union[str, Sequence[str], None] = '3b99fd207f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('songs', 'create_at')
    # ### end Alembic commands ###
